language: node_js
node_js:
  - "7.0"
  - "6.0"
  - "5.0"
  - "4.0"
sudo: false
script:
  - "npm run travis"
addons:
  code_climate:
    repo_token: 5bfed542b6b6d5706451d09ec65561c9ea9015d93eda411b9036585115a20132
after_success:
  - npm install -g codeclimate-test-reporter
  - CODECLIMATE_REPO_TOKEN=5bfed542b6b6d5706451d09ec65561c9ea9015d93eda411b9036585115a20132 codeclimate-test-reporter < coverage/lcov.info
